date_tag: "250923"
dataset_number: 0

base_path: "/dataNAS/people/nurdaiza/saved_data/"
data_info_filename: "./data_info.json"

# Reconstruction control
R_eff: 4                    # per interleave
do_sense_subspace: true
do_filter_recon: false

# Sparsity / constraints
lamda_sparsity: [0.0, 0.0, 0.0]
do_constrain_ngc: false
sparsity_domain: "wavelet"

# Slice / echo selection
slices_to_process: [10, 13]     # begin and end indices
echoes_to_use: 7

# ESPIRiT calibration
N_acs: 32
espirit_crop: 0.7
espirit_thresh: 0.05
max_iter_calib: 20

# Unaliasing / reconstruction
max_iter_unalias: 20
lamda_calib: 1e-6
lamda_unalias: 1e-6

# Data handling
polarity_index: null
do_sort_bipolar_data: true

plot_results: false
